import mongoose from "mongoose";

const itemSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "users",
        required: true
    },
    // Source information
    url: {
        type: String,
        require: true,
        default: null
    },

    // Content metadata
    title: {
        type: String,
        require: true,
        default: []
    },
    description: String,
    tags: [String],   // Generated by AI
    image: String,
    siteName: String,

    // Content
    content: String,     // Extracted text from article/pdf
    contentType: {
        type: String,
        enum: ["article", "tweet", "image", "video", "pdf", "file", "other"],
        default: 'other'
    },

    // File (If user uploaded)
    file: {
        storagePath: String,
        fileUrl: String,
        mimeType: String,
        fileSize: Number,
        originalFileName: String
    },

    // Search & recomendations
    chromaId: {
        type: String,
        sparse: true
    },

    collectionId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "collection"
    },

    // Timestamps
    createAt: {
        type: Date,
        default: Date.now
    },

    updatedAt: {
        type: Date,
        default: Date.now
    },

    // Resurfacing 
    lastResurfaceDate: Date,
    resurfaceCount: {
        type: Number,
        default: 0
    }
}, { timestamps: true})

export const itemModel = mongoose.model("items", itemSchema)